# Workspaces and Niri-like scroller defaults
tag_num=9
tagrule=id:*,layout_name:scroller

# Spacing and decoration geometry
gappih=16
gappiv=16
gappoh=16
gappov=16
borderpx=4
border_radius=20
no_radius_when_single=0
no_border_when_single=0

scroller_default_proportion=0.5
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.33333,0.5,0.66667
scroller_focus_center=0
