# Keep all coordinates positive because negative coordinates break pointer input
# in XWayland. DP-8 is left of the scaled 4K display.
monitorrule=name:^DP-7$,width:3840,height:2160,refresh:120,x:2560,y:0,scale:1.5,vrr:1,rr:0
monitorrule=name:^DP-8$,width:2560,height:1440,refresh:143.998,x:0,y:0,scale:1,vrr:0,rr:0
